AWSTemplateFormatVersion: 2010-09-09
Description: Create target bucket to store rg-deployment-docs
Resources:
  IMDSv2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: "RG-IMDSv2"
      LaunchTemplateData:
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 1
          HttpTokens: required

  ProjectAccountAccessLogsBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key for Deployment Access logs bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM Policies
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"

  ProjectAccountAccessLogsBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 bucket hosting access logs shouldn't have access logging configured
    Properties:
      BucketName:
        !Join 
          - "-"
          - - "rg-project-account-accesslogs"
            - !Ref "AWS::AccountId"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt ProjectAccountAccessLogsBucketKMSKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  ProjectAccountAccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProjectAccountAccessLogsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ServerAccessLogsPolicy-DeploymentBucket
            Action:
              - "s3:PutObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${ProjectAccountAccessLogsBucket}/*"
            Principal:
              Service: logging.s3.amazonaws.com
            Condition:
              StringEquals:
                "aws:SourceAccount":
                  - !Sub "${AWS::AccountId}"

Outputs:
  ProjectAccountAccessLogsBucket:
    Description: Name of the project account access logs bucket
    Value: !Ref ProjectAccountAccessLogsBucket

  ProjectAccountAccessLogsBucketKMSKey:
    Description: The KMS key used to encrypt the Project account access logs bucket
    Value: !GetAtt ProjectAccountAccessLogsBucketKMSKey.Arn
