AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Research Gateway Amazon Linux 2 Patch Baseline'

Resources:
  rgAmazonLinuxPatchline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: rg-AWS-AmazonLinuxDefaultPatchBaseline
      Description: Patch Baseline for Research Gateway(RG) Amazon Linux 2 Provided by AWS.
      OperatingSystem: AMAZON_LINUX_2
      PatchGroups:
        - RG-PatchGroup-Linux
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              PatchFilters:
                - Key: PRODUCT
                  Values:
                    - AmazonLinux2
                    - AmazonLinux2.0
                - Key: SEVERITY
                  Values:
                    - Critical
                    - Important
                - Key: CLASSIFICATION
                  Values:
                    - Security
                    - Recommended
                    - Bugfix          
            ApproveAfterDays: 7
            ComplianceLevel: CRITICAL
