AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Lambda function using Node.js 18.x

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function
    AllowedPattern: ^[a-zA-Z0-9-\-_.]{3,63}
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda zip file
  S3ObjectKey:
    Type: String
    Description: Key of the Lambda zip file in the S3 bucket

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: EgressLambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: RGLambdaBasics
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Sid: AllowEgressLambdaToCopyFromStoreToNotification
                Effect: "Allow"
                Action:
                  -  "s3:*"
                  -  "s3-object-lambda:*"
                  -  "kms:*"
                Resource: "*"
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3ObjectKey
      Tags:
        - Key: CostCenter
          Value: PG000000
        - Key: CriticalityTier
          Value: Business Operational
        - Key: Compliance
          Value: HIPAA
        - Key: Environment
          Value: PROD
        - Key: ApplicationName
          Value: ResearchGatewayPROD
        - Key: Department
          Value: DataScience
        - Key: ApplicationCustodian
          Value: txs908
        - Key: ServiceNow
          Value: XXX
        - Key: departmentemail
          Value: txs908@miami.edu
        - Key: UHITOwner
          Value: txs908
  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref LambdaFunction
      AuthType: AWS_IAM
Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: LambdaFunctionArn
  FunctionUrl:
    Description: Lambda Function Url
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl
