AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template to create security groups with specific ingress and egress rules for a given VPC.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the security groups will be created.

Resources:
  EntryPointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: entrypointSG
      GroupDescription: Security Group for EntryPoint
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  WorkspaceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: workspaceSG
      GroupDescription: Security Group for Workspace
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref EntryPointSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  InterfaceEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: interfaceEndpointSG
      GroupDescription: Security Group for Interface Endpoint
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref WorkspaceSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  EntryPointSG:
    Description: Security Group ID for EntryPoint
    Value: !Ref EntryPointSecurityGroup

  WorkspaceSG:
    Description: Security Group ID for Workspace
    Value: !Ref WorkspaceSecurityGroup

  InterfaceEndpointSG:
    Description: Security Group ID for Interface Endpoint
    Value: !Ref InterfaceEndpointSecurityGroup