AWSTemplateFormatVersion: '2010-09-09'
Description: create a single S3 bucket

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names 
  KMSKeyArn:
    Type: String
    Description: "If having KMS Key ARN, Pass ARN"
    Default: "Default"
  SSEAlgorithm:
    Type: String
    Description: "If KMS key ARN passed,select aws:kms Encryption algorithm"
    Default: "AES256"
    AllowedValues:
      - aws:kms
      - AES256

Conditions:
  AES256: !Equals [!Ref SSEAlgorithm, "AES256"]   

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Namespace    
      Tags:
        - Key: cost_resource
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${Namespace} 

Outputs:
  BucketArn:
    Value: !GetAtt [SampleBucket, Arn]
    Description: URL for website hosted on S3
  BucketName:
    Value: !Ref SampleBucket
    Description: Name of S3 bucket