AWSTemplateFormatVersion: "2010-09-09"
Description: create a single S3 bucket

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  AccessLoggingBucketName:
    Type: String
    Description: "Pass the bucket name where Access Logs for this S3 bucket should be sent"
    Default: ""
  AccessLoggingBucketPrefix:
    Type: String
    Description: "Pass the bucket prefix where Access Logs for this S3 bucket should be sent"
    Default: "/"

Conditions:
  AccessLoggingEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: AccessLoggingBucketName
          - ""

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Namespace
      Tags:
        - Key: cost_resource
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${Namespace}
      LoggingConfiguration:
        Fn::If:
          - AccessLoggingEnabled
          - DestinationBucketName: !Ref AccessLoggingBucketName
            LogFilePrefix: !Ref AccessLoggingBucketPrefix
          - !Ref "AWS::NoValue"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref SampleBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: EnforceTLS12
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${SampleBucket.Arn}"
              - !Sub "${SampleBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
          - Sid: EnforceTLS12OrHigher
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${SampleBucket.Arn}"
              - !Sub "${SampleBucket.Arn}/*"
            Condition:
              NumericLessThan:
                "s3:TLSVersion": "1.2"

Outputs:
  BucketArn:
    Value: !GetAtt [SampleBucket, Arn]
    Description: URL for website hosted on S3
  BucketName:
    Value: !Ref SampleBucket
    Description: Name of S3 bucket
